### ISSUE TITLE
toggling between sample_xhr.html and sample.html does not work

### ISSUE THREAD

**Issue by sChalvet** [domoinc/domo-node-embed-filters#4]
In express.js `process.env.USE_XHR  ? 'sample_xhr.html' : 'sample.html'` on line 107 always evaluates too true since it comes in as a string from the `.env` file.

It should instead be `process.env.USE_XHR === 'true' ? 'sample_xhr.html' : 'sample.html'` for it to work as expected.

**Comment by john-aldridge** [comment]
Thank you for pointing out this issue and for the fix. I have incorporated your fix into the most recent code.
